name: Vulnerability Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write

jobs:
  vulnerability-scan:
    uses: kaatinga/go-vulnerability-scan/.github/workflows/vulnerability-scan.yml@main
    with:
      go-version: '1.25'
      go-package: './...'
      cache-dependency-path: 'go.sum,go.work.sum'
      upload-sarif: false  # Disabled for private repo
